// Le 70 caselle de "Il Drago Alcolico". Il campo `effect` è valorizzato solo
// per le caselle il cui testo descrive uno spostamento sul tabellone
// inequivocabile (es. "salta/torna alla casella N", "avanza/indietreggia di
// N caselle", scambio o furto di caselle): quello spostamento viene applicato
// automaticamente dal gioco. Tutte le altre regole (sorsi, sfide, penitenze,
// scelte del gruppo, condizioni reali come "se devi andare in bagno") restano
// solo testo mostrato nel modale: sono i giocatori a gestirle a voce.
// `nome` è un titolo breve mostrato sulla casella, per orientarsi a colpo
// d'occhio sul tabellone senza dover aprire il modale.
export const CELLS = [
  { numero: 1, tipo: 'inizio', nome: 'Partenza', testo: "Partenza! Fate un brindisi inaugurale: 1 sorso per tutti.", effect: null },
  { numero: 2, tipo: 'sorso', nome: 'Scaldamotori', testo: "Bevi 1 sorso per scaldate i motori.", effect: null },
  { numero: 3, tipo: 'sfida', nome: 'Carta Sasso Forbice', testo: "Sasso-Carta-Forbice col giocatore a tua destra. Chi perde beve 2 sorsi.", effect: null },
  { numero: 4, tipo: 'penitenza', nome: 'the more you know', testo: "Il giocatore alla tua sinistra ti indica un argomento devi nominare 3 cose inerenti ad esso in 5 secondi o bevi 2 sorsi.", effect: null },
  { numero: 5, tipo: 'drago', nome: 'Soffio del Drago', testo: "Soffio del Drago! Salta avanti alla casella 10.", effect: { type: 'moveTo', value: 10 } },
  { numero: 6, tipo: 'gruppo', nome: 'Bevono i Ragazzi', testo: "Tutti i ragazzi bevono 1 sorso.", effect: null },
  { numero: 7, tipo: 'sorso', nome: 'Sorsi dal Dado', testo: "Bevi tanti sorsi quanti sono la metà dei punti fatti con i dadi in questo turno.", effect: null },
  { numero: 8, tipo: 'sfida', nome: 'Il Complimento', testo: "Fai un complimento al giocatore alla tua sinistra o bevi 2 sorsi.", effect: null },
  { numero: 9, tipo: 'imprevisto', nome: 'Distribuisci Sorsi', testo: "Distribuisci 3 sorsi a chi vuoi tu.", effect: null },
  { numero: 10, tipo: 'drago', nome: 'Tana del Drago', testo: "La Tana del Drago! Bevi 1 shot o 3 sorsi abbondanti.", effect: null },
  { numero: 11, tipo: 'gruppo', nome: 'Bevono le Ragazze', testo: "Tutte le ragazze bevono 1 sorso altrimenti bevono tutti", effect: null },
  { numero: 12, tipo: 'penitenza', nome: 'Dito sul Naso', testo: "Metti un dito sul naso: l'ultimo giocatore che lo fa beve 2 sorsi.", effect: null },
  { numero: 13, tipo: 'sfortuna', nome: 'Venerdì 13', testo: "Venerdì 13! Torna alla casella 8 e bevi 1 sorso.", effect: { type: 'moveTo', value: 8 } },
  { numero: 14, tipo: 'sfida', nome: 'Gara di Sguardi', testo: "Gara di sguardi con chi ti sta di fronte. Chi ride o sbattendo le palpebre perde e beve 2 sorsi.", effect: null },
  { numero: 15, tipo: 'regola', nome: 'Nuova Regola', testo: "Crea una regola valida fino al prossimo turno (es. vietato usare i nomi propri).", effect: null },
  { numero: 16, tipo: 'sorso', nome: 'Due Sorsi', testo: "Bevi 2 sorsi.", effect: null },
  { numero: 17, tipo: 'imprevisto', nome: 'Scambio di Posto', testo: "Scambia la tua posizione con il giocatore più indietro.", effect: { type: 'swapWithLast' } },
  { numero: 18, tipo: 'drago', nome: 'Ali del Drago', testo: "Ali del Drago! Vola alla casella 23.", effect: { type: 'moveTo', value: 23 } },
  { numero: 19, tipo: 'penitenza', nome: 'Accento Straniero', testo: "Parla con un accento straniero fino al tuo prossimo turno o bevi 3 sorsi.", effect: null },
  { numero: 20, tipo: 'gruppo', nome: 'Chi Veste di Nero', testo: "Chi indossa qualcosa di nero beve 1 sorso.", effect: null },
  { numero: 21, tipo: 'sfida', nome: 'Flessioni', testo: "Fai 3 flessioni/piegamenti o bevi 3 sorsi.", effect: null },
  { numero: 22, tipo: 'sorso', nome: 'Compagno di Bevute', testo: "Scegli un 'compagno di bevute': per i prossimi 3 turni beve ogni volta che bevi tu.", effect: null },
  { numero: 23, tipo: 'imprevisto', nome: 'Sorsi per Lettera', testo: "Distribuisci tanti sorsi quanto il numero di lettere del tuo nome.", effect: null },
  { numero: 24, tipo: 'sfortuna', nome: 'Pausa Bagno Tassata', testo: "Tassa pausa bagno! per andare al bagno bisogna bere 3, dura fino all'inizio del tuo prossimo turno", effect: null },
  { numero: 25, tipo: 'penitenza', nome: 'Canta o Bevi', testo: "Fai la ruota o un salto mortale... Scherzo! Canta il ritornello di una canzone o bevi 2 sorsi.", effect: null },
  { numero: 26, tipo: 'drago', nome: 'Morso del Drago', testo: "Morso del Drago! Bevi 3 sorsi e torna indietro di 2 caselle.", effect: { type: 'moveBy', value: -2 } },
  { numero: 27, tipo: 'gruppo', nome: 'I Più Giovani', testo: "Tutti quelli che sono più giovani di te bevono 1 sorso.", effect: null },
  { numero: 28, tipo: 'sfida', nome: 'Catena di Rime', testo: "Inizia una catena di rime. Chi sbaglia o ci mette più di 3 secondi beve 2 sorsi.", effect: null },
  { numero: 29, tipo: 'sorso', nome: 'Sorsi dal Percorso', testo: "Bevi 1 sorso per ogni casella di cui ti sei mosso in questo turno.", effect: null },
  { numero: 30, tipo: 'special', nome: 'Metà Strada', testo: "Meta strada! Brindisi generale di metà percorso.", effect: null },
  { numero: 31, tipo: 'penitenza', nome: 'Foto Imbarazzante', testo: "Rivela la tua foto più imbarazzante sul telefono o bevi 3 sorsi.", effect: null },
  { numero: 32, tipo: 'imprevisto', nome: 'Il Più Sobrio', testo: "Dai 2 sorsi al giocatore più sobrio del tavolo.", effect: null },
  { numero: 33, tipo: 'drago', nome: 'Premio di Ruggero', testo: "Ruggero il Drago ti premia! Avanza di 3 caselle.", effect: { type: 'moveBy', value: 3 } },
  { numero: 34, tipo: 'gruppo', nome: 'Batteria Scarica', testo: "Chi ha il telefono al 50% di carica o meno beve 2 sorsi.", effect: null },
  { numero: 35, tipo: 'sfida', nome: 'Dire o Fare', testo: "Dire o Fare: rispondi a una domanda scomoda del gruppo o bevi uno shot.", effect: null },
  { numero: 36, tipo: 'sorso', nome: 'Senza Mani', testo: "Bevi 2 sorsi senza usare le mani o cannuccia.", effect: null },
  { numero: 37, tipo: 'sfortuna', nome: 'Gabbia del Drago', testo: "Gabbia del Drago! Resta immobile fino al tuo prossimo turno a meno che qualcuno non beva 2 sorsi per te, ogni volta che ti muovi bevi", effect: null },
  { numero: 38, tipo: 'penitenza', nome: 'Storia Instagram', testo: "Lascia che il giocatore alla tua destra ti mandi una storia su Instagram o bevi 4 sorsi.", effect: null },
  { numero: 39, tipo: 'gruppo', nome: 'Più Follower', testo: "Il giocatore con più follower su Instagram beve 2 sorsi.", effect: null },
  { numero: 40, tipo: 'drago', nome: 'Fuoco del Drago', testo: "Fuoco del Drago! Bevi 1 shot.", effect: null },
  { numero: 41, tipo: 'imprevisto', nome: 'Due Sorsi Insieme', testo: "Scegli una persona che deve fare 2 sorsi con te.", effect: null },
  { numero: 42, tipo: 'sfida', nome: 'Silenzio Forzato', testo: "Non rispondere a nessuna domanda fino al tuo prossimo turno. Se rispondi, bevi 3 sorsi.", effect: null },
  { numero: 43, tipo: 'sorso', nome: "Tre Sorsi d'un Fiato", testo: "Bevi 3 sorsi d'un fiato.", effect: null },
  { numero: 44, tipo: 'penitenza', nome: 'Mimo', testo: "Il giocatore alla tua destra di dice cosa mimare. Se nessuno indovina entro 30 secondi, bevi 2 sorsi.", effect: null },
  { numero: 45, tipo: 'sfortuna', nome: 'Ritorno alla 35', testo: "Torna alla casella 35.", effect: { type: 'moveTo', value: 35 } },
  { numero: 46, tipo: 'gruppo', nome: 'I Single Bevono', testo: "Tutti i single bevono 2 sorsi.", effect: null },
  { numero: 47, tipo: 'drago', nome: 'Squama di Drago', testo: "Squama di Drago! Sei immune a tutto per i prossimi 2 lanci di dado.", effect: null },
  { numero: 48, tipo: 'imprevisto', nome: 'Brindisi Dedicato', testo: "Fai un brindisi dedicato a qualcuno al tavolo. Tutti bevono 1 sorso.", effect: null },
  { numero: 49, tipo: 'sfida', nome: 'Equilibrio', testo: "Tieni in equilibrio un bicchiere sulla testa per 10 secondi o bevi 2 sorsi.", effect: null },
  { numero: 50, tipo: 'penitenza', nome: 'Una Gamba Sola', testo: "Rimani in piedi su una gamba sola fino al prossimo turno o bevi 2 sorsi.", effect: null },
  { numero: 51, tipo: 'gruppo', nome: 'Fidanzati e Sposati', testo: "Tutti i fidanzati/sposati bevono 2 sorsi.", effect: null },
  { numero: 52, tipo: 'sorso', nome: 'Bevi e Dai', testo: "Scegli qualcuno con cui bere 1", effect: null },
  { numero: 53, tipo: 'drago', nome: 'Artiglio del Drago', testo: "Artiglio del Drago! Ruba 2 caselle al giocatore in testa.", effect: { type: 'stealFromLeader', value: 2 } },
  { numero: 54, tipo: 'imprevisto', nome: 'Pari o Dispari', testo: "Lancia una moneta: se esce testa bevi tu, se esce croce bevono tutti gli altri.", effect: null },
  { numero: 55, tipo: 'sfida', nome: 'Il Segreto', testo: "Di' un segreto o una curiosità che nessuno sa su di te, oppure bevi 3 sorsi.", effect: null },
  { numero: 56, tipo: 'sfortuna', nome: 'Inversione di Rotta', testo: "Inversione di rotta! Tutti i giocatori tornano indietro di 3 caselle.", effect: { type: 'allMoveBy', value: -3 } },
  { numero: 57, tipo: 'penitenza', nome: 'Bacio sulla Guancia', testo: "Bacia sulla guancia il giocatore alla tua sinistra o bevi 2 sorsi.", effect: null },
  { numero: 58, tipo: 'gruppo', nome: 'Ultimo del Drink', testo: "L'ultimo che finisce il proprio drink beve uno shot.", effect: null },
  { numero: 59, tipo: 'drago', nome: 'Risveglio del Drago', testo: "Il Risveglio del Drago! Tutti tranne te bevono 2 sorsi.", effect: null },
  { numero: 60, tipo: 'sorso', nome: 'Sorsi Abbondanti forse', testo: "Bevi 3 sorsi abbondanti. se lo fai tutti gli altri ne bevono 4 come i tuoi", effect: null },
  { numero: 61, tipo: 'sfida', nome: "Dichiarazione d'Amore", testo: "Fai una dichiarazione d'amore drammatica a una sedia o bevi 3 sorsi.", effect: null },
  { numero: 62, tipo: 'imprevisto', nome: 'Quasi alla Fine', testo: "Sei vicino alla fine! Scegli due persone che devono bere 2 sorsi ciascuna.", effect: null },
  { numero: 63, tipo: 'penitenza', nome: 'Il Solletico', testo: "Lasciati fare un solletico per 10 secondi senza ridere o bevi 3 sorsi.", effect: null },
  { numero: 64, tipo: 'sfortuna', nome: 'Vento del Drago', testo: "Vento del Drago! Torna indietro alla casella 55.", effect: { type: 'moveTo', value: 55 } },
  { numero: 65, tipo: 'gruppo', nome: 'Tiro Basso', testo: "Tutti quelli che hanno fatto un tiro col dado inferiore a 4 nel loro ultimo turno bevono 2 sorsi.", effect: null },
  { numero: 66, tipo: 'drago', nome: 'Sguardo del Drago', testo: "Sguardo del Drago! Fino al tuo prossimo turno all inizio di ogni turno devi scegliere un giocatore che beve 1 con te ", effect: null },
  { numero: 67, tipo: 'sorso', nome: 'Quattro Sorsi', testo: "Bevi 4 sorsi.", effect: null },
  { numero: 68, tipo: 'imprevisto', nome: 'Penultima Casella', testo: "Penultima casella! Distribuisci 5 sorsi come preferisci.", effect: null },
  { numero: 69, tipo: 'sfortuna', nome: 'Così Vicino', testo: "Così vicino ma così lontano! Torna alla casella 60 e bevi 2 sorsi.", effect: { type: 'moveTo', value: 60 } },
  { numero: 70, tipo: 'fine', nome: 'Sei un Drago', testo: "VITTORIA! Hai sconfitto il Drago Alcolico! Gli altri giocatori devono fare uno shot in tuo onore!", effect: null },
];
